UCDOC 3067 - Add WhiteSource plugin docs
UrbanCode/IBM-UCx-PLUGIN-DOCS-OLD pull request #115
Opened 2022-11-23 05:54 UTC by Naveennkg

2022-11-23 08:06 UTC, osmanburucu-ibm commented on docs/UCV/ucv-ext-whitesource/downloads.md
> +TestNG - Downloads
Shouldn't this be Whitesource instead of TestNG?

2022-11-23 08:08 UTC, osmanburucu-ibm requested changes
* the downloads.md contains TestNG instead of Whitesource
* please remove the README.md.bak

2022-11-23 14:37 UTC, Naveennkg commented on docs/UCV/ucv-ext-whitesource/downloads.md
> +TestNG - Downloads
Yes, it must be WhiteSource.

2022-11-24 06:53 UTC, osmanburucu-ibm approved these changes
Thank You!

2022-11-24 06:53 UTC, merged